baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Vítor Fróis'

[taxonomies]
	tag = "tags"

[permalinks]
	blog = "/:filename/"

[params]
	dateFormat = 'Jan 02, 2006'

[markup]
	defaultMarkdownHandler = "pandoc"
  [markup.pandoc]
    lua-filter = "static/lua/tikz.lua"
  [tableOfContents]
    startLevel = 1
    ordered = true
    endLevel = 4
  [highlight]
    linenos = true

[security.exec]
  allow = ['^pandoc$']


[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "Resume"
    pre = "resume"
    url = "/resume/resume.pdf"
    weight = 4

